/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroDeFuncionarioController;
import Model.CadastroDeFuncionarioModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNO
 */
public class TelaCadastroDeFuncionario extends javax.swing.JFrame {

    CadastroDeFuncionarioController controler = new CadastroDeFuncionarioController();
    /**
     * Creates new form Casdastrodefuncionario
     */
    public TelaCadastroDeFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nomecompleto = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        cpfFuncionario = new javax.swing.JFormattedTextField();
        datadenacimento = new javax.swing.JLabel();
        dataNascimentoFuncionario = new javax.swing.JFormattedTextField();
        genero = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        email = new javax.swing.JLabel();
        emailFuncionario = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        senhaFuncionario = new javax.swing.JPasswordField();
        cadastrarFuncionario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        fone = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        voltafuncionario = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        menuFuncionario = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomecompleto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomecompleto.setText("NOME COMPLETO:");
        jPanel1.add(nomecompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 24));

        nomeFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        nomeFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        nomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(nomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 460, 30));

        cpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cpf.setForeground(new java.awt.Color(255, 255, 255));
        cpf.setText("CPF:");
        jPanel1.add(cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        cpfFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        cpfFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        try {
            cpfFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cpfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 270, 30));

        datadenacimento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        datadenacimento.setForeground(new java.awt.Color(255, 255, 255));
        datadenacimento.setText("DATA DE NASCIMENTO: ");
        jPanel1.add(datadenacimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 190, -1));

        dataNascimentoFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        dataNascimentoFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        try {
            dataNascimentoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataNascimentoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dataNascimentoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataNascimentoFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(dataNascimentoFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 150, 30));

        genero.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        genero.setForeground(new java.awt.Color(255, 255, 255));
        genero.setText("GENÊRO:");
        jPanel1.add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 80, -1));

        sexo.setBackground(new java.awt.Color(102, 0, 102));
        sexo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sexo.setForeground(new java.awt.Color(255, 255, 255));
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Masculino", "Feminino" }));
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 230, 30));

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-MAIL:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, -1));

        emailFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        emailFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(emailFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 480, 30));

        senha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        senha.setForeground(new java.awt.Color(255, 255, 255));
        senha.setText("SENHA:");
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 70, -1));

        senhaFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        senhaFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        senhaFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(senhaFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 290, 30));

        cadastrarFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        cadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cadastrarFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarFuncionario.setText("CADASTRAR");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 130, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO DE FUNCIONARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 290, 47));

        editar.setBackground(new java.awt.Color(102, 0, 102));
        editar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("EDITAR");
        jPanel1.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, -1, -1));

        excluir.setBackground(new java.awt.Color(102, 0, 102));
        excluir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setText("EXCLUIR");
        jPanel1.add(excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        fone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fone.setForeground(new java.awt.Color(255, 255, 255));
        fone.setText("FONE:");
        jPanel1.add(fone, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 50, -1));

        telefone.setBackground(new java.awt.Color(102, 0, 102));
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        jPanel1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 190, 30));

        voltafuncionario.setBackground(new java.awt.Color(102, 0, 102));
        voltafuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltafuncionario.setForeground(new java.awt.Color(255, 255, 255));
        voltafuncionario.setText("VOLTAR");
        voltafuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltafuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(voltafuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 110, -1));

        tabelaFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        tabelaFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome do Funcionário", "Data de Nascimento", "Telefone", "CPF", "Email", "Senha", "Genêro"
            }
        ));
        jScrollPane1.setViewportView(tabelaFuncionario);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 940, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastro (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1240, 660));

        botaoHome.setText("HOME");
        menuFuncionario.add(botaoHome);

        setJMenuBar(menuFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nomeFuncionarioActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here   
   
        CadastroDeFuncionarioModel funcionario = new CadastroDeFuncionarioModel();
        // cadastrar os dentro da classe CadastroDeFuncionarioModel
        // getText() funciona apenas para compos do tipo TextField
        funcionario.setNomeFuncionario((String)nomeFuncionario.getText());
        funcionario.setDatanascimentoFuncionario((String)dataNascimentoFuncionario.getText());
        funcionario.setTelefoneFuncionario((String)telefone.getText());
        funcionario.setCpfFuncionario((String)cpfFuncionario.getText());
        funcionario.setSexo((String)sexo.getSelectedItem());
        funcionario.setEmailFuncionario((String)emailFuncionario.getText());
        funcionario.setSenhaFuncionario(new String (senhaFuncionario.getPassword()));
        
        
      
        
        if(controler.CadastroDeFuncionario(funcionario)){
             JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null,"Erro ao realizar cadastro!");
        }
        
        /*if (result != false){
            JOptionPane.showMessageDialog(null, "Cadastro de funcionario realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }*/
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void dataNascimentoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataNascimentoFuncionarioActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void cpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFuncionarioActionPerformed

    private void voltafuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltafuncionarioActionPerformed
        // TODO add your handling code here:
        TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltafuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoHome;
    private javax.swing.JButton cadastrarFuncionario;
    private javax.swing.JLabel cpf;
    private javax.swing.JFormattedTextField cpfFuncionario;
    private javax.swing.JFormattedTextField dataNascimentoFuncionario;
    private javax.swing.JLabel datadenacimento;
    private javax.swing.JButton editar;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailFuncionario;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel fone;
    private javax.swing.JLabel genero;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuBar menuFuncionario;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JLabel nomecompleto;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhaFuncionario;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JTable tabelaFuncionario;
    private javax.swing.JFormattedTextField telefone;
    private javax.swing.JToggleButton voltafuncionario;
    // End of variables declaration//GEN-END:variables
}
