/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Model.ClienteModel;
import javax.swing.JOptionPane;


/**
 *
 * @author ALUNO
 */
public class TelaCadastroDeCliente extends javax.swing.JFrame {
    
    ClienteController controler = new ClienteController();
    /**
     * Creates new form telaCadastro
     */
    public TelaCadastroDeCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro1 = new javax.swing.JPanel();
        telefoneCliente = new javax.swing.JFormattedTextField();
        nomeCompleto = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        campoCpf = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereço = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JTextField();
        emailCliente = new javax.swing.JTextField();
        nomeCompletocampo = new javax.swing.JTextField();
        cadastrarCliente = new javax.swing.JButton();
        tenhoConta = new javax.swing.JLabel();
        cpfCliente = new javax.swing.JFormattedTextField();
        cadastro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        butonHome = new javax.swing.JMenu();
        butonCliente = new javax.swing.JMenu();
        butonFuncionarios = new javax.swing.JMenu();
        butonPlanos = new javax.swing.JMenu();
        butonMaquinas = new javax.swing.JMenu();
        butonCaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCadastro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefoneCliente.setBackground(new java.awt.Color(102, 0, 102));
        telefoneCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            telefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        painelCadastro1.add(telefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 340, 30));

        nomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        nomeCompleto.setText("NOME COMPLETO:");
        painelCadastro1.add(nomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-MAIL:");
        painelCadastro1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        campoCpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(255, 255, 255));
        campoCpf.setText("CPF:");
        painelCadastro1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        telefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("TELEFONE:");
        painelCadastro1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        endereço.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        endereço.setForeground(new java.awt.Color(255, 255, 255));
        endereço.setText("ENDEREÇO:");
        painelCadastro1.add(endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        enderecoCliente.setBackground(new java.awt.Color(102, 0, 102));
        enderecoCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        enderecoCliente.setForeground(new java.awt.Color(255, 255, 255));
        enderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoClienteActionPerformed(evt);
            }
        });
        painelCadastro1.add(enderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 340, 30));

        emailCliente.setBackground(new java.awt.Color(102, 0, 102));
        emailCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailCliente.setForeground(new java.awt.Color(255, 255, 255));
        emailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailClienteActionPerformed(evt);
            }
        });
        painelCadastro1.add(emailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 340, -1));

        nomeCompletocampo.setBackground(new java.awt.Color(102, 0, 102));
        nomeCompletocampo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nomeCompletocampo.setForeground(new java.awt.Color(255, 255, 255));
        painelCadastro1.add(nomeCompletocampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 340, -1));

        cadastrarCliente.setBackground(new java.awt.Color(102, 102, 102));
        cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarCliente.setText("CADASTRAR");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        painelCadastro1.add(cadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 120, 30));

        tenhoConta.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        tenhoConta.setForeground(new java.awt.Color(255, 255, 255));
        tenhoConta.setText("Já tenho uma conta");
        tenhoConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenhoContaMouseClicked(evt);
            }
        });
        painelCadastro1.add(tenhoConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        cpfCliente.setBackground(new java.awt.Color(102, 0, 102));
        cpfCliente.setForeground(new java.awt.Color(255, 255, 255));
        try {
            cpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        painelCadastro1.add(cpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 340, 30));
        painelCadastro1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, -10, 1040, 680));

        butonHome.setText("HOME");
        jMenuBar1.add(butonHome);

        butonCliente.setText("CLIENTE");
        jMenuBar1.add(butonCliente);

        butonFuncionarios.setText("FUNCIONÁRIO");
        jMenuBar1.add(butonFuncionarios);

        butonPlanos.setText("PLANOS");
        jMenuBar1.add(butonPlanos);

        butonMaquinas.setText("MÁQUINAS");
        jMenuBar1.add(butonMaquinas);

        butonCaixa.setText("CAIXA");
        butonCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonCaixaMouseClicked(evt);
            }
        });
        jMenuBar1.add(butonCaixa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoClienteActionPerformed

    private void emailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailClienteActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
       ClienteModel cliente = new ClienteModel();

      cliente.setNomeCliente((String)nomeCompletocampo.getText());
      cliente.setEmailCliente((String)emailCliente.getText());
      cliente.setCpfCliente((String)cpfCliente.getText());
      cliente.setTelefoneCliente((String)telefoneCliente.getText());
      cliente.setEnderecoCliente((String)enderecoCliente.getText());
     
      // boolean result = controler.CadastroCliente(cliente);
            
      if (controler.CadastroCliente(cliente)!=false){
            JOptionPane.showMessageDialog(null, "Cadastro de cliente realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void tenhoContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenhoContaMouseClicked
        // TODO add your handling code here:
  
    }//GEN-LAST:event_tenhoContaMouseClicked

    private void butonCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonCaixaMouseClicked
        // TODO add your handling code here:
 
       
    }//GEN-LAST:event_butonCaixaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu butonCaixa;
    private javax.swing.JMenu butonCliente;
    private javax.swing.JMenu butonFuncionarios;
    private javax.swing.JMenu butonHome;
    private javax.swing.JMenu butonMaquinas;
    private javax.swing.JMenu butonPlanos;
    private javax.swing.JButton cadastrarCliente;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JFormattedTextField cpfCliente;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JTextField enderecoCliente;
    private javax.swing.JLabel endereço;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nomeCompleto;
    private javax.swing.JTextField nomeCompletocampo;
    private javax.swing.JPanel painelCadastro1;
    private javax.swing.JLabel telefone;
    private javax.swing.JFormattedTextField telefoneCliente;
    private javax.swing.JLabel tenhoConta;
    // End of variables declaration//GEN-END:variables
}
