/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


/**
 *
 * @author ALUNO
 */
public class TelaCadastroDePlano extends javax.swing.JFrame {

    /**
     * Creates new form cadastroPlano2
     */
    public TelaCadastroDePlano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaadesao = new javax.swing.JLabel();
        cadastrodeplano = new javax.swing.JLabel();
        taxa = new javax.swing.JTextField();
        statusplano = new javax.swing.JLabel();
        nomeplano = new javax.swing.JLabel();
        ativodesetivo = new javax.swing.JComboBox<>();
        driscricaodoplano = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        plano = new javax.swing.JTextField();
        mudar = new javax.swing.JButton();
        apaga = new javax.swing.JButton();
        valormensal = new javax.swing.JLabel();
        preco = new javax.swing.JTextField();
        nomeparaplano = new javax.swing.JTextField();
        imagemfundo = new javax.swing.JLabel();
        menuPlano = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();
        botaoCliente = new javax.swing.JMenu();
        botaoFuncionario = new javax.swing.JMenu();
        botaoPlanos = new javax.swing.JMenu();
        botaoMaquinas = new javax.swing.JMenu();
        botaoCaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taxaadesao.setBackground(new java.awt.Color(102, 0, 102));
        taxaadesao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taxaadesao.setForeground(new java.awt.Color(255, 255, 255));
        taxaadesao.setText("TAXA DE ADESÃO: ");
        jPanel1.add(taxaadesao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        cadastrodeplano.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cadastrodeplano.setForeground(new java.awt.Color(255, 255, 255));
        cadastrodeplano.setText("CADASTRO DE PLANO");
        jPanel1.add(cadastrodeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, -1));

        taxa.setBackground(new java.awt.Color(102, 0, 102));
        taxa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(taxa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 150, 30));

        statusplano.setBackground(new java.awt.Color(102, 0, 102));
        statusplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusplano.setForeground(new java.awt.Color(255, 255, 255));
        statusplano.setText("STATUS DO PLANO: ");
        jPanel1.add(statusplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));

        nomeplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeplano.setForeground(new java.awt.Color(255, 255, 255));
        nomeplano.setText("NOME DO PLANO:");
        jPanel1.add(nomeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, -1));

        ativodesetivo.setBackground(new java.awt.Color(102, 0, 102));
        ativodesetivo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ativodesetivo.setForeground(new java.awt.Color(255, 255, 255));
        ativodesetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        ativodesetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativodesetivoActionPerformed(evt);
            }
        });
        jPanel1.add(ativodesetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));

        driscricaodoplano.setBackground(new java.awt.Color(102, 0, 102));
        driscricaodoplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        driscricaodoplano.setForeground(new java.awt.Color(255, 255, 255));
        driscricaodoplano.setText("DESCRIÇÃO DO PLANO: ");
        jPanel1.add(driscricaodoplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 140, -1, -1));

        salvar.setBackground(new java.awt.Color(102, 0, 102));
        salvar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        salvar.setForeground(new java.awt.Color(255, 255, 255));
        salvar.setText("SALVAR");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        plano.setBackground(new java.awt.Color(102, 0, 102));
        plano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        plano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(plano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 420, 30));

        mudar.setBackground(new java.awt.Color(102, 0, 102));
        mudar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mudar.setForeground(new java.awt.Color(255, 255, 255));
        mudar.setText("EDITAR");
        jPanel1.add(mudar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        apaga.setBackground(new java.awt.Color(102, 0, 102));
        apaga.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        apaga.setForeground(new java.awt.Color(255, 255, 255));
        apaga.setText("EXCLUIR");
        apaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagaActionPerformed(evt);
            }
        });
        jPanel1.add(apaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        valormensal.setBackground(new java.awt.Color(102, 0, 102));
        valormensal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        valormensal.setForeground(new java.awt.Color(255, 255, 255));
        valormensal.setText("VALOR MENSAL:");
        jPanel1.add(valormensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        preco.setBackground(new java.awt.Color(102, 0, 102));
        preco.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        preco.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(preco, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, 30));

        nomeparaplano.setBackground(new java.awt.Color(102, 0, 102));
        nomeparaplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeparaplano.setForeground(new java.awt.Color(255, 255, 255));
        nomeparaplano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeparaplanoActionPerformed(evt);
            }
        });
        jPanel1.add(nomeparaplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 450, 30));
        jPanel1.add(imagemfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 6, 930, 520));

        botaoHome.setText("HOME");
        menuPlano.add(botaoHome);

        botaoCliente.setText("CLIENTE");
        menuPlano.add(botaoCliente);

        botaoFuncionario.setText("FUNCIONÁIO");
        menuPlano.add(botaoFuncionario);

        botaoPlanos.setText("PLANOS");
        menuPlano.add(botaoPlanos);

        botaoMaquinas.setText("MÁQUINAS");
        menuPlano.add(botaoMaquinas);

        botaoCaixa.setText("CAIXA");
        menuPlano.add(botaoCaixa);

        setJMenuBar(menuPlano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeparaplanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeparaplanoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nomeparaplanoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    private void ativodesetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativodesetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativodesetivoActionPerformed

    private void apagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apagaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDePlano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apaga;
    private javax.swing.JComboBox<String> ativodesetivo;
    private javax.swing.JMenu botaoCaixa;
    private javax.swing.JMenu botaoCliente;
    private javax.swing.JMenu botaoFuncionario;
    private javax.swing.JMenu botaoHome;
    private javax.swing.JMenu botaoMaquinas;
    private javax.swing.JMenu botaoPlanos;
    private javax.swing.JLabel cadastrodeplano;
    private javax.swing.JLabel driscricaodoplano;
    private javax.swing.JLabel imagemfundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuPlano;
    private javax.swing.JButton mudar;
    private javax.swing.JTextField nomeparaplano;
    private javax.swing.JLabel nomeplano;
    private javax.swing.JTextField plano;
    private javax.swing.JTextField preco;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel statusplano;
    private javax.swing.JTextField taxa;
    private javax.swing.JLabel taxaadesao;
    private javax.swing.JLabel valormensal;
    // End of variables declaration//GEN-END:variables






}
