/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaHome
     */
    public TelaHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoIconeCliente = new javax.swing.JButton();
        botaoIconeFuncionario = new javax.swing.JButton();
        botaoIconePlanos = new javax.swing.JButton();
        botaoIconeMaquinas = new javax.swing.JButton();
        botaoIconeCaixa = new javax.swing.JButton();
        botaopCliente = new javax.swing.JButton();
        botaopFuncionario = new javax.swing.JButton();
        botaopPlanos = new javax.swing.JButton();
        botaopMaquinas = new javax.swing.JButton();
        botaopCaixa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();
        botaoCliente = new javax.swing.JMenu();
        botaoFuncionario = new javax.swing.JMenu();
        botaoPlanos = new javax.swing.JMenu();
        botaoMaquinas = new javax.swing.JMenu();
        botaoCaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoIconeCliente.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/client.png"))); // NOI18N
        jPanel1.add(botaoIconeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 136, 98, 110));

        botaoIconeFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoIconeFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        jPanel1.add(botaoIconeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 136, 99, 110));

        botaoIconePlanos.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconePlanos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoIconePlanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planning.png"))); // NOI18N
        jPanel1.add(botaoIconePlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 136, 101, 112));

        botaoIconeMaquinas.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeMaquinas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaoIconeMaquinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monitoring.png"))); // NOI18N
        jPanel1.add(botaoIconeMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 113, 109));

        botaoIconeCaixa.setBackground(new java.awt.Color(255, 255, 255));
        botaoIconeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/budget.png"))); // NOI18N
        jPanel1.add(botaoIconeCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 315, 104, 109));

        botaopCliente.setBackground(new java.awt.Color(102, 0, 102));
        botaopCliente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaopCliente.setForeground(new java.awt.Color(255, 255, 255));
        botaopCliente.setText("CLIENTE");
        jPanel1.add(botaopCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 254, 98, -1));

        botaopFuncionario.setBackground(new java.awt.Color(102, 0, 102));
        botaopFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaopFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        botaopFuncionario.setText("FUNCIONÁRIOS");
        jPanel1.add(botaopFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 254, -1, -1));

        botaopPlanos.setBackground(new java.awt.Color(102, 0, 102));
        botaopPlanos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaopPlanos.setForeground(new java.awt.Color(255, 255, 255));
        botaopPlanos.setText("PLANOS");
        botaopPlanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaopPlanosActionPerformed(evt);
            }
        });
        jPanel1.add(botaopPlanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 254, 100, -1));

        botaopMaquinas.setBackground(new java.awt.Color(102, 0, 102));
        botaopMaquinas.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaopMaquinas.setForeground(new java.awt.Color(255, 255, 255));
        botaopMaquinas.setText("MÁQUINAS");
        jPanel1.add(botaopMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        botaopCaixa.setBackground(new java.awt.Color(102, 0, 102));
        botaopCaixa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        botaopCaixa.setForeground(new java.awt.Color(255, 255, 255));
        botaopCaixa.setText("CAIXA");
        jPanel1.add(botaopCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 104, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALUNO\\Downloads\\Cadastro (2).png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 640));

        botaoHome.setText("HOME");
        jMenuBar1.add(botaoHome);

        botaoCliente.setText("CLIENTE");
        jMenuBar1.add(botaoCliente);

        botaoFuncionario.setText("FUNCIONÁRIO");
        jMenuBar1.add(botaoFuncionario);

        botaoPlanos.setText("PLANOS");
        jMenuBar1.add(botaoPlanos);

        botaoMaquinas.setText("MÁQUINAS");
        jMenuBar1.add(botaoMaquinas);

        botaoCaixa.setText("CAIXA");
        jMenuBar1.add(botaoCaixa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaopPlanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaopPlanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaopPlanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoCaixa;
    private javax.swing.JMenu botaoCliente;
    private javax.swing.JMenu botaoFuncionario;
    private javax.swing.JMenu botaoHome;
    private javax.swing.JButton botaoIconeCaixa;
    private javax.swing.JButton botaoIconeCliente;
    private javax.swing.JButton botaoIconeFuncionario;
    private javax.swing.JButton botaoIconeMaquinas;
    private javax.swing.JButton botaoIconePlanos;
    private javax.swing.JMenu botaoMaquinas;
    private javax.swing.JMenu botaoPlanos;
    private javax.swing.JButton botaopCaixa;
    private javax.swing.JButton botaopCliente;
    private javax.swing.JButton botaopFuncionario;
    private javax.swing.JButton botaopMaquinas;
    private javax.swing.JButton botaopPlanos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
