/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.MonitoramentoController;
import Model.MonitoramentoModel;
import View.TelaMonitoramento;
import javax.swing.JOptionPane;



/**
 *
 * @author ALUNO
 */
public class TelaNovoAparelho extends javax.swing.JFrame {
    
    MonitoramentoController controler = new MonitoramentoController();

    /**
     * Creates new form TelaNovoAparelho
     */
    public TelaNovoAparelho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        voltarnovoaparelho = new javax.swing.JButton();
        confirmaraparelho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tipoaparelho = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        nomeaparelho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NOVO APARELHO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 22, -1, -1));

        voltarnovoaparelho.setBackground(new java.awt.Color(102, 0, 102));
        voltarnovoaparelho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarnovoaparelho.setForeground(new java.awt.Color(255, 255, 255));
        voltarnovoaparelho.setText("VOLTAR");
        voltarnovoaparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarnovoaparelhoActionPerformed(evt);
            }
        });
        jPanel1.add(voltarnovoaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 277, 121, -1));

        confirmaraparelho.setBackground(new java.awt.Color(102, 0, 102));
        confirmaraparelho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmaraparelho.setForeground(new java.awt.Color(255, 255, 255));
        confirmaraparelho.setText("CADASTRAR");
        confirmaraparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmaraparelhoActionPerformed(evt);
            }
        });
        jPanel1.add(confirmaraparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 277, 108, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPO DE APARELHO: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 79, -1, -1));

        tipoaparelho.setBackground(new java.awt.Color(102, 0, 102));
        tipoaparelho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tipoaparelho.setForeground(new java.awt.Color(255, 255, 255));
        tipoaparelho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VIDEO GAME", "COMPUTADOR", "SIMULADOR" }));
        jPanel1.add(tipoaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 74, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOME DO APARELHO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 111, -1, -1));

        nomeaparelho.setBackground(new java.awt.Color(102, 0, 102));
        nomeaparelho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeaparelho.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nomeaparelho, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 106, 193, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 480, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaraparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaraparelhoActionPerformed
        // TODO add your handling code here:
        MonitoramentoModel novoAparelho = new MonitoramentoModel();
        
        novoAparelho.setTipoMaquina((String)tipoaparelho.getSelectedItem());
        novoAparelho.setNomeMaquina((String)nomeaparelho.getText()); 
     
        boolean result = controler.Monitoramento(novoAparelho);
        
        if (result != false){
            JOptionPane.showMessageDialog(null, "Cadastro de aparelho realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }
    }//GEN-LAST:event_confirmaraparelhoActionPerformed

    private void voltarnovoaparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarnovoaparelhoActionPerformed
        // TODO add your handling code here:
        TelaMonitoramento retornatela = new TelaMonitoramento();
        retornatela.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarnovoaparelhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaNovoAparelho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaNovoAparelho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmaraparelho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeaparelho;
    private javax.swing.JComboBox<String> tipoaparelho;
    private javax.swing.JButton voltarnovoaparelho;
    // End of variables declaration//GEN-END:variables
}
