/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaEsqueceuSenha extends javax.swing.JFrame {

    /**
     * Creates new form TelaEsqueciSenha
     */
    public TelaEsqueceuSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelEsqueciSenha = new javax.swing.JPanel();
        emailEsqueciSenha = new javax.swing.JLabel();
        novaSenha = new javax.swing.JLabel();
        repitaSenha = new javax.swing.JLabel();
        campoNovaSenha = new javax.swing.JPasswordField();
        redefinirSenha = new javax.swing.JButton();
        voltaTelaLogin = new javax.swing.JButton();
        tituloEsqueciSenha = new javax.swing.JLabel();
        formatoSenha = new javax.swing.JPasswordField();
        campoEsqueciSenhaCpf = new javax.swing.JFormattedTextField();
        butonLayuot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelEsqueciSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailEsqueciSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        emailEsqueciSenha.setForeground(new java.awt.Color(255, 255, 255));
        emailEsqueciSenha.setText("CPF:");
        painelEsqueciSenha.add(emailEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        novaSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        novaSenha.setForeground(new java.awt.Color(255, 255, 255));
        novaSenha.setText("NOVA SENHA:");
        painelEsqueciSenha.add(novaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        repitaSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        repitaSenha.setForeground(new java.awt.Color(255, 255, 255));
        repitaSenha.setText("REPITA A SENHA:");
        painelEsqueciSenha.add(repitaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        campoNovaSenha.setBackground(new java.awt.Color(102, 0, 102));
        campoNovaSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoNovaSenha.setForeground(new java.awt.Color(255, 255, 255));
        campoNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNovaSenhaActionPerformed(evt);
            }
        });
        painelEsqueciSenha.add(campoNovaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 350, -1));

        redefinirSenha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        redefinirSenha.setText("Redefinir");
        redefinirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redefinirSenhaMouseClicked(evt);
            }
        });
        painelEsqueciSenha.add(redefinirSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        voltaTelaLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        voltaTelaLogin.setText("Volta");
        voltaTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaTelaLoginActionPerformed(evt);
            }
        });
        painelEsqueciSenha.add(voltaTelaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        tituloEsqueciSenha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        tituloEsqueciSenha.setForeground(new java.awt.Color(255, 255, 255));
        tituloEsqueciSenha.setText("Redefiniçao de Senha");
        painelEsqueciSenha.add(tituloEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        formatoSenha.setBackground(new java.awt.Color(102, 0, 102));
        formatoSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        formatoSenha.setForeground(new java.awt.Color(255, 255, 255));
        formatoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatoSenhaActionPerformed(evt);
            }
        });
        painelEsqueciSenha.add(formatoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 350, -1));

        campoEsqueciSenhaCpf.setBackground(new java.awt.Color(102, 0, 102));
        campoEsqueciSenhaCpf.setForeground(new java.awt.Color(255, 255, 255));
        try {
            campoEsqueciSenhaCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelEsqueciSenha.add(campoEsqueciSenhaCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 350, -1));
        painelEsqueciSenha.add(butonLayuot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEsqueciSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEsqueciSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNovaSenhaActionPerformed

    private void voltaTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaTelaLoginActionPerformed
        // TODO add your handling code here:
        TelaLogin loginls= new TelaLogin();
        loginls.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_voltaTelaLoginActionPerformed

    private void redefinirSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redefinirSenhaMouseClicked
        // TODO add your handling code here:
        TelaLogin logints= new TelaLogin();
        logints.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_redefinirSenhaMouseClicked

    private void formatoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEsqueceuSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEsqueceuSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel butonLayuot;
    private javax.swing.JFormattedTextField campoEsqueciSenhaCpf;
    private javax.swing.JPasswordField campoNovaSenha;
    private javax.swing.JLabel emailEsqueciSenha;
    private javax.swing.JPasswordField formatoSenha;
    private javax.swing.JLabel novaSenha;
    private javax.swing.JPanel painelEsqueciSenha;
    private javax.swing.JButton redefinirSenha;
    private javax.swing.JLabel repitaSenha;
    private javax.swing.JLabel tituloEsqueciSenha;
    private javax.swing.JButton voltaTelaLogin;
    // End of variables declaration//GEN-END:variables
}
