/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author ALUNO
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel1 = new javax.swing.JPanel();
        campoCpf = new javax.swing.JLabel();
        varivelSenha = new javax.swing.JLabel();
        butomLogin = new javax.swing.JButton();
        butonEsqueciSenha = new javax.swing.JLabel();
        senhaLogin = new javax.swing.JFormattedTextField();
        campoCpf1 = new javax.swing.JFormattedTextField();
        paonelLayout1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCpf.setBackground(new java.awt.Color(255, 255, 255));
        campoCpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(255, 255, 255));
        campoCpf.setText("CPF:");
        painel1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 20));

        varivelSenha.setBackground(new java.awt.Color(255, 255, 255));
        varivelSenha.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        varivelSenha.setForeground(new java.awt.Color(255, 255, 255));
        varivelSenha.setText("SENHA:");
        painel1.add(varivelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 120, 60));

        butomLogin.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        butomLogin.setText("LOGIN");
        butomLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butomLoginMouseClicked(evt);
            }
        });
        butomLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butomLoginActionPerformed(evt);
            }
        });
        painel1.add(butomLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, -1, -1));

        butonEsqueciSenha.setBackground(new java.awt.Color(102, 102, 102));
        butonEsqueciSenha.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        butonEsqueciSenha.setForeground(new java.awt.Color(255, 255, 255));
        butonEsqueciSenha.setText("esqueci a senha");
        butonEsqueciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonEsqueciSenhaMouseClicked(evt);
            }
        });
        painel1.add(butonEsqueciSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        senhaLogin.setBackground(new java.awt.Color(102, 0, 102));
        senhaLogin.setForeground(new java.awt.Color(255, 255, 255));
        try {
            senhaLogin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        senhaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLoginActionPerformed(evt);
            }
        });
        painel1.add(senhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 290, -1));

        campoCpf1.setBackground(new java.awt.Color(102, 0, 102));
        try {
            campoCpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painel1.add(campoCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 290, -1));
        painel1.add(paonelLayout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 490));

        getContentPane().add(painel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butomLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butomLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butomLoginActionPerformed

    private void butonEsqueciSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonEsqueciSenhaMouseClicked
        // TODO add your handling code here:
        TelaEsqueceuSenha esquecish= new TelaEsqueceuSenha();
        esquecish.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_butonEsqueciSenhaMouseClicked

    private void butomLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butomLoginMouseClicked
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_butomLoginMouseClicked

    private void senhaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butomLogin;
    private javax.swing.JLabel butonEsqueciSenha;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JFormattedTextField campoCpf1;
    private javax.swing.JPanel painel1;
    private javax.swing.JLabel paonelLayout1;
    private javax.swing.JFormattedTextField senhaLogin;
    private javax.swing.JLabel varivelSenha;
    // End of variables declaration//GEN-END:variables
}
