/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastrodeplanoController;
import Model.Cadastrodeplano;
import javax.swing.JOptionPane;


/**
 *
 * @author ALUNO
 */
public class TelaCadastroDePlano extends javax.swing.JFrame {
    
    CadastrodeplanoController controler = new CadastrodeplanoController(); 
    /**
     * Creates new form cadastroPlano2
     */
    public TelaCadastroDePlano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        taxaadesao = new javax.swing.JLabel();
        cadastrodeplano = new javax.swing.JLabel();
        taxaPlano = new javax.swing.JTextField();
        statusplano = new javax.swing.JLabel();
        nomeplano = new javax.swing.JLabel();
        statusPlano = new javax.swing.JComboBox<>();
        driscricaodoplano = new javax.swing.JLabel();
        cadastroPlano = new javax.swing.JButton();
        descricaoPlano = new javax.swing.JTextField();
        editarPlano = new javax.swing.JButton();
        excluirPlano = new javax.swing.JButton();
        valormensal = new javax.swing.JLabel();
        valorPlano = new javax.swing.JTextField();
        nomePlano = new javax.swing.JTextField();
        voltarMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPlano = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        menuPlano = new javax.swing.JMenuBar();
        botaoHome = new javax.swing.JMenu();
        botaoCliente = new javax.swing.JMenu();
        botaoFuncionario = new javax.swing.JMenu();
        botaoPlanos = new javax.swing.JMenu();
        botaoMaquinas = new javax.swing.JMenu();
        botaoCaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taxaadesao.setBackground(new java.awt.Color(102, 0, 102));
        taxaadesao.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taxaadesao.setForeground(new java.awt.Color(255, 255, 255));
        taxaadesao.setText("TAXA DE ADESÃO: ");
        jPanel1.add(taxaadesao, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        cadastrodeplano.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cadastrodeplano.setForeground(new java.awt.Color(255, 255, 255));
        cadastrodeplano.setText("CADASTRO DE PLANO");
        jPanel1.add(cadastrodeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 220, -1));

        taxaPlano.setBackground(new java.awt.Color(102, 0, 102));
        taxaPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taxaPlano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(taxaPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 150, 30));

        statusplano.setBackground(new java.awt.Color(102, 0, 102));
        statusplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusplano.setForeground(new java.awt.Color(255, 255, 255));
        statusplano.setText("STATUS DO PLANO: ");
        jPanel1.add(statusplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, 20));

        nomeplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeplano.setForeground(new java.awt.Color(255, 255, 255));
        nomeplano.setText("NOME DO PLANO:");
        jPanel1.add(nomeplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, -1));

        statusPlano.setBackground(new java.awt.Color(102, 0, 102));
        statusPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusPlano.setForeground(new java.awt.Color(255, 255, 255));
        statusPlano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Desativado" }));
        statusPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(statusPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));

        driscricaodoplano.setBackground(new java.awt.Color(102, 0, 102));
        driscricaodoplano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        driscricaodoplano.setForeground(new java.awt.Color(255, 255, 255));
        driscricaodoplano.setText("DESCRIÇÃO DO PLANO: ");
        jPanel1.add(driscricaodoplano, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 140, -1, -1));

        cadastroPlano.setBackground(new java.awt.Color(102, 0, 102));
        cadastroPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cadastroPlano.setForeground(new java.awt.Color(255, 255, 255));
        cadastroPlano.setText("CADASTRAR");
        cadastroPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(cadastroPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        descricaoPlano.setBackground(new java.awt.Color(102, 0, 102));
        descricaoPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        descricaoPlano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(descricaoPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 420, 30));

        editarPlano.setBackground(new java.awt.Color(102, 0, 102));
        editarPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        editarPlano.setForeground(new java.awt.Color(255, 255, 255));
        editarPlano.setText("EDITAR");
        jPanel1.add(editarPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        excluirPlano.setBackground(new java.awt.Color(102, 0, 102));
        excluirPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        excluirPlano.setForeground(new java.awt.Color(255, 255, 255));
        excluirPlano.setText("EXCLUIR");
        excluirPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPlanoActionPerformed(evt);
            }
        });
        jPanel1.add(excluirPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        valormensal.setBackground(new java.awt.Color(102, 0, 102));
        valormensal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        valormensal.setForeground(new java.awt.Color(255, 255, 255));
        valormensal.setText("VALOR MENSAL:");
        jPanel1.add(valormensal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        valorPlano.setBackground(new java.awt.Color(102, 0, 102));
        valorPlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        valorPlano.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(valorPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 140, 30));

        nomePlano.setBackground(new java.awt.Color(102, 0, 102));
        nomePlano.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomePlano.setForeground(new java.awt.Color(255, 255, 255));
        nomePlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomePlanoActionPerformed(evt);
            }
        });
        jPanel1.add(nomePlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 450, 30));

        voltarMenu.setBackground(new java.awt.Color(102, 0, 102));
        voltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        voltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        voltarMenu.setText("VOLTAR");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(voltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 100, -1));

        tabelaPlano.setBackground(new java.awt.Color(102, 0, 102));
        tabelaPlano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do Plano", "Descrição do Plano", "Valor", "Status do Plano", "Adesão"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaPlano);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 600, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastro (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1310, 580));

        botaoHome.setText("HOME");
        menuPlano.add(botaoHome);

        botaoCliente.setText("CLIENTE");
        menuPlano.add(botaoCliente);

        botaoFuncionario.setText("FUNCIONÁRIO");
        menuPlano.add(botaoFuncionario);

        botaoPlanos.setText("PLANOS");
        menuPlano.add(botaoPlanos);

        botaoMaquinas.setText("MÁQUINAS");
        menuPlano.add(botaoMaquinas);

        botaoCaixa.setText("CAIXA");
        menuPlano.add(botaoCaixa);

        setJMenuBar(menuPlano);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomePlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomePlanoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nomePlanoActionPerformed

    private void cadastroPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroPlanoActionPerformed
        // TODO add your handling code here:
       Cadastrodeplano plano = new Cadastrodeplano();
         
      plano.setNomePlano((String)nomePlano.getText());
      plano.setDescricaoPlano((String)descricaoPlano.getText());
      plano.setValorPlano(Double.parseDouble(valorPlano.getText()));
      plano.setTaxaPlano(Double.parseDouble(taxaPlano.getText()));
      plano.setStatusPlano((String)statusPlano.getSelectedItem());
      
      boolean result = controler.Cadastrodeplano(plano);
      
       /*if(controler.Cadastrodeplano(plano)){
           JOptionPane.showMessageDialog(null,"Cadastro com sucesso");
       } else {   
          JOptionPane.showMessageDialog(null,"Erro ao realizar");
        }*/
        if (result!=false){
            JOptionPane.showMessageDialog(null, "Cadastro de plano realizado com sucesso");
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar");
        }
    }//GEN-LAST:event_cadastroPlanoActionPerformed

    private void statusPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusPlanoActionPerformed

    private void excluirPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPlanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirPlanoActionPerformed

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        // TODO add your handling code here:
        TelaHome voltarMenu = new TelaHome() ;
        voltarMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDePlano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDePlano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu botaoCaixa;
    private javax.swing.JMenu botaoCliente;
    private javax.swing.JMenu botaoFuncionario;
    private javax.swing.JMenu botaoHome;
    private javax.swing.JMenu botaoMaquinas;
    private javax.swing.JMenu botaoPlanos;
    private javax.swing.JButton cadastroPlano;
    private javax.swing.JLabel cadastrodeplano;
    private javax.swing.JTextField descricaoPlano;
    private javax.swing.JLabel driscricaodoplano;
    private javax.swing.JButton editarPlano;
    private javax.swing.JButton excluirPlano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menuPlano;
    private javax.swing.JTextField nomePlano;
    private javax.swing.JLabel nomeplano;
    private javax.swing.JComboBox<String> statusPlano;
    private javax.swing.JLabel statusplano;
    private javax.swing.JTable tabelaPlano;
    private javax.swing.JTextField taxaPlano;
    private javax.swing.JLabel taxaadesao;
    private javax.swing.JTextField valorPlano;
    private javax.swing.JLabel valormensal;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables






}
