/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Model.ClienteModel;
import View.TelaCadastroDePlano;
import javax.swing.JOptionPane;


/**
 *
 * @author ALUNO
 */
public class TelaCadastroDeCliente extends javax.swing.JFrame {

    ClienteController controler = new ClienteController();


    /**
     * Creates new form telaCadastro
     */
    public TelaCadastroDeCliente(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCadastro1 = new javax.swing.JPanel();
        nomeCompleto = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        campoCpf = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        endereço = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        nomeCompletocampo = new javax.swing.JTextField();
        cadastrarCliente = new javax.swing.JButton();
        campoCpf1 = new javax.swing.JFormattedTextField();
        cadastro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        butonHome = new javax.swing.JMenu();
        butonCliente = new javax.swing.JMenu();
        butonFuncionarios = new javax.swing.JMenu();
        butonPlanos = new javax.swing.JMenu();
        butonMaquinas = new javax.swing.JMenu();
        butonCaixa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelCadastro1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeCompleto.setForeground(new java.awt.Color(255, 255, 255));
        nomeCompleto.setText("NOME COMPLETO:");
        painelCadastro1.add(nomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, -1));

        email.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-MAIL:");
        painelCadastro1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        campoCpf.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoCpf.setForeground(new java.awt.Color(255, 255, 255));
        campoCpf.setText("CPF:");
        painelCadastro1.add(campoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        telefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("TELEFONE:");
        painelCadastro1.add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        endereço.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        endereço.setForeground(new java.awt.Color(255, 255, 255));
        endereço.setText("ENDEREÇO:");
        painelCadastro1.add(endereço, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        campoEndereco.setBackground(new java.awt.Color(102, 0, 102));
        campoEndereco.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoEndereco.setForeground(new java.awt.Color(255, 255, 255));
        campoEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 340, 30));

        campoTelefone.setBackground(new java.awt.Color(102, 0, 102));
        campoTelefone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoTelefone.setForeground(new java.awt.Color(255, 255, 255));
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 340, -1));

        campoEmail.setBackground(new java.awt.Color(102, 0, 102));
        campoEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        campoEmail.setForeground(new java.awt.Color(255, 255, 255));
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        painelCadastro1.add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 340, -1));

        nomeCompletocampo.setBackground(new java.awt.Color(102, 0, 102));
        nomeCompletocampo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        nomeCompletocampo.setForeground(new java.awt.Color(255, 255, 255));
        nomeCompletocampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCompletocampoActionPerformed(evt);
            }
        });
        painelCadastro1.add(nomeCompletocampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 340, -1));

        cadastrarCliente.setBackground(new java.awt.Color(102, 102, 102));
        cadastrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarCliente.setText("CADASTRAR");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });
        painelCadastro1.add(cadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 120, 30));

        campoCpf1.setBackground(new java.awt.Color(102, 0, 102));
        campoCpf1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            campoCpf1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelCadastro1.add(campoCpf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 340, 30));
        painelCadastro1.add(cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 1040, 680));

        butonHome.setText("HOME");
        jMenuBar1.add(butonHome);

        butonCliente.setText("CLIENTE");
        jMenuBar1.add(butonCliente);

        butonFuncionarios.setText("FUNCIONÁRIO");
        jMenuBar1.add(butonFuncionarios);

        butonPlanos.setText("PLANOS");
        jMenuBar1.add(butonPlanos);

        butonMaquinas.setText("MÁQUINAS");
        jMenuBar1.add(butonMaquinas);

        butonCaixa.setText("CAIXA");
        butonCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butonCaixaMouseClicked(evt);
            }
        });
        jMenuBar1.add(butonCaixa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelCadastro1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
      ClienteModel cliente = new ClienteModel();

      cliente.setNomeCliente((String)nomeCompletocampo.getText());
      cliente.setEmailCliente((String)campoEmail.getText());
      cliente.setCpfCliente((String)campoCpf1.getText());
      cliente.setTelefoneCliente((String)campoTelefone.getText());
      cliente.setEnderecoCliente((String)campoEndereco.getText());
      

      boolean result = controler.CadastroCliente(cliente);
      
      if (result!=false){
          JOptionPane.showMessageDialog(null,"Cadastro do cliente realizado com sucesso");
      }else{
          JOptionPane.showMessageDialog(null,"Falha ao cadastra cliente");
      }      
      
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void butonCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butonCaixaMouseClicked
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_butonCaixaMouseClicked

    private void nomeCompletocampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCompletocampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletocampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroDeCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroDeCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu butonCaixa;
    private javax.swing.JMenu butonCliente;
    private javax.swing.JMenu butonFuncionarios;
    private javax.swing.JMenu butonHome;
    private javax.swing.JMenu butonMaquinas;
    private javax.swing.JMenu butonPlanos;
    private javax.swing.JButton cadastrarCliente;
    private javax.swing.JLabel cadastro;
    private javax.swing.JLabel campoCpf;
    private javax.swing.JFormattedTextField campoCpf1;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereço;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel nomeCompleto;
    private javax.swing.JTextField nomeCompletocampo;
    private javax.swing.JPanel painelCadastro1;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
